cpus:
- 2
- 4

log_dir: /tmp/experiments/
n_resas: 0
net_workers:
- dp: CFCFS
  ip: 127.0.0.1
  is_echo: 0
  port: 8080
network:
  device_id: 0
  eal_init:
  - -n
  - '2'
  - -l
  - 0, 2
  - --file-prefix
  - maxdml
  - -w
  - '0000:18:00.1'
  mac: '42:42:42:42:42:01'
requests:
- type: NOISY
- type: VICTIM
workers:
  number: 4
  type: MySQLDB
