cpus:
- 2
log_dir: /tmp/experiments/
net_workers:
- ip: 127.0.0.1
  port: 8080
network:
  device_id: 0
  eal_init:
  - -n
  - '2'
  - -l
  - 0, 2
  - --file-prefix
  - maxdml
  - -w
  - '0000:18:00.1'
  mac: '42:42:42:42:42:02'
  remote_mac: '42:42:42:42:42:01'
schedules:
- cmd_mean_ns:
  - 1000000000
  cmd_ratios:
  - 0.01
  duration: 10
  ptype: NOISY
  rate: 0
  uniform: false
